from uuid import UUID

from pydantic import BaseModel, Field


class RetrievedChunk(BaseModel):
    """A document chunk retrieved from the vector store."""

    chunk_id: UUID
    document_id: UUID
    content: str
    score: float


class RAGContext(BaseModel):
    """Structured evidence context passed to the LLM."""

    query: str
    chunks: list[RetrievedChunk] = Field(default_factory=list)
    context: str = ""


class RAGResponse(BaseModel):
    """Final response generated by the RAG pipeline."""

    answer: str
    sources: list[RetrievedChunk] = Field(default_factory=list)